### ISSUE TITLE
Have you finished it now? It doesn't work at the moment.

### ISSUE THREAD

**Issue by wanliyunyan** [Ashrafty/app_v2ray_manager#1]
I used your previous project（[RAE-VPN](https://github.com/Ashrafty/RAE-VPN)）, and it worked well. However, with this one, whenever I connect to the VPN, my phone can't connect to any network

**Comment by Ashrafty** [comment]
am still working on this fixing some bugs i'll update as soon as am able to as for [RAE-VPN](https://github.com/Ashrafty/RAE-VPN) i'll also update it some time in the future
